### ISSUE TITLE
Ideal way to update dependencies version

### ISSUE THREAD

**Issue by levint** [electrodejs/generator-electrode#53]
Question:

How to properly update react/react-dom to current version?

====
Following http://www.electrode.io/docs/build_with_material_ui.html would lead to an error upon running `gulp dev`, some modules found in `react-dom` cannot be resolved due to the fact that the latest `react-tap-event-plugin`  requires react-dom >=15.4. Some other dependencies on the latest `material-ui` package depends on react >=15.4

**Comment by ananavati** [comment]
react & react-dom dependencies are using caret(^) and hence npm should be installing the latest 15.4.x version.

what version of npm are you using?
